<?php

namespace Database\Seeders;

use App\Models\DataKonflikSosial;
use App\Models\DataSarprasKerja;
use App\Models\DataSejahteraKeluarga;
use App\Models\DataSosialEkonomi;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder {
    public function run(): void {
        $this->call([
            RoleSeeder::class,
            UserSeeder::class,
            
            MasterAsetKeluargaSeeder::class,
            MasterAgamaSeeder::class,
            MasterAktaNikahSeeder::class,
            MasterAsetLahanSeeder::class,
            MasterAsetPerikananSeeder::class,
            MasterAsetTernakSeeder::class,
            MasterBahanBakarMemasakSeeder::class,
            MasterCaraPembuanganSampahSeeder::class,
            MasterCaraPerolehanAirSeeder::class,
            MasterWilayahLengkapSeeder::class,
            MasterDusunSeeder::class,
            MasterFasilitasTempatBabSeeder::class,
            MasterHubunganKeluargaSeeder::class,
            MasterHubunganKepalaKeluargaSeeder::class,
            MasterImunisasiSeeder::class,
            MasterInventarisSeeder::class,
            MasterIjasahTerakhirSeeder::class,
            MasterJabatanSeeder::class,
            MasterJawabBangunSeeder::class,
            MasterJawabKonflikSeeder::class,
            MasterJawabKualitasBayiSeeder::class,
            MasterJawabKualitasIbuHamilSeeder::class,
            MasterJawabLemdesSeeder::class,
            MasterJawabLemekSeeder::class,
            MasterJawabLemmasSeeder::class,
            MasterJawabProgramSertaSeeder::class,
            MasterJawabSeeder::class,
            MasterJawabSarprasSeeder::class,
            MasterJawabTempatPersalinanSeeder::class,
            MasterJenisAtapBangunanSeeder::class,
            MasterJenisBahanGalianSeeder::class,
            MasterJenisDindingBangunanSeeder::class,
            MasterJenisDisabilitasSeeder::class,
            MasterJenisFisikBangunanSeeder::class,
            MasterJenisKelahiranSeeder::class,
            MasterJenisKelaminSeeder::class,
            MasterJenisLantaiBangunanSeeder::class,
            MasterKartuIdentitasSeeder::class,
            MasterKondisiAtapBangunanSeeder::class,
            MasterKondisiDindingBangunanSeeder::class,
            MasterKondisiLantaiBangunanSeeder::class,
            MasterKondisiLapanganUsahaSeeder::class,
            MasterKondisiSumberAirSeeder::class,
            MasterKonflikSosialSeeder::class,
            MasterKualitasBayiSeeder::class,
            MasterKualitasIbuHamilSeeder::class,
            MasterLapanganUsahaSeeder::class,
            MasterLembagaSeeder::class,
            MasterManfaatMataAirSeeder::class,
            MasterMutasiKeluarSeeder::class,
            MasterMutasiMasukSeeder::class,
            MasterOmsetUsahaSeeder::class,
            MasterPartisipasiSekolahSeeder::class,
            MasterPekerjaanSeeder::class,
            MasterPembangunanKeluargaSeeder::class,
            MasterPembuanganAkhirTinjaSeeder::class,
            MasterPendapatanPerbulanSeeder::class,
            MasterPenyakitKronisSeeder::class,
            MasterPertolonganPersalinanSeeder::class,
            MasterProgramSertaSeeder::class,
            MasterSarprasKerjaSeeder::class,
            MasterStatusKawinSeeder::class,
            MasterStatusKedudukanKerjaSeeder::class,
            MasterStatusPemilikBangunanSeeder::class,
            MasterStatusPemilikLahanSeeder::class,
            MasterStatusTinggalSeeder::class,
            MasterSumberAirMinumSeeder::class,
            MasterSumberDayaTerpasangSeeder::class,
            MasterSumberPeneranganUtamaSeeder::class,
            MasterTempatPersalinanSeeder::class,
            MasterTempatUsahaSeeder::class,
            MasterTercantumDalamKKSeeder::class,
            MasterTingkatSulitDisabilitasSeeder::class,
            MasterJawabLahanSeeder::class,
            
            DataPendudukSeeder::class,
            DataAsetKeluargaSeeder::class,
            DataAsetLahanSeeder::class,
            DataPrasaranaDasarSeeder::class,
            DataSejahteraKeluargaSeeder::class,
            DataKonflikSosialSeeder::class,
            DataSarprasKerjaSeeder::class,
            DataBangunKeluargaSeeder::class,
            DataAsetTernakSeeder::class,
            DataAsetPerikananSeeder::class,
            DataLembagaDesaSeeder::class,
            DataLembagaEkonomiSeeder::class,
            DataLembagaMasyarakatSeeder::class,
            DataProgramSertaSeeder::class,
            DataSosialEkonomiSeeder::class,
            DataUsahaArtSeeder::class,
            DataKelahiranSeeder::class,
            DataKualitasIbuHamilSeeder::class,
            DataKualitasBayiSeeder::class
        ]);
    }
}
